supplement.json: webpack-dev-server
Trying to resolve the `webpack-dev-server: command not found` error. I
think this means that webpack-dev-server needs to be installed globally
(so it'll be available in the shell environment). So I added it in
supplement.json and ran the following:

  nix-shell \
      --packages nodePackages.node2nix \
      --run 'node2nix --development --supplement-input supplement.json -8 -l package-lock.json'

Once this finished, I tried it out:

  nix-shell -A shell

This fails with the following error:

  client-src/default doesn't exist

A more complete log of the error:

  $ nix-shell -A shell
  these derivations will be built:
  ...

  ...
  npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
  npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
  npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

  > webpack-dev-server@2.11.2 prepublish /nix/store/qvr8n6lvbv3iq87wl7wppkjx6iq4yxxn-node-webpack-dev-server-2.11.2/lib/node_modules/webpack-dev-server
  > (rm ssl/*.pem || true) && npm run -s transpile:index && npm run -s build:live && npm run -s build:index && npm run -s build:sockjs

  rm: cannot remove 'ssl/*.pem': No such file or directory
  client-src/default doesn't exist
  npm ERR! code ELIFECYCLE
  npm ERR! errno 2
  npm ERR! webpack-dev-server@2.11.2 prepublish: `(rm ssl/*.pem || true) && npm run -s transpile:index && npm run -s build:live && npm run -s build:index && npm run -s build:sockjs`
  npm ERR! Exit status 2
  npm ERR!
  npm ERR! Failed at the webpack-dev-server@2.11.2 prepublish script.
  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

  npm ERR! A complete log of this run can be found in:
  npm ERR!     /tmp/nix-build-node-webpack-dev-server-2.11.2.drv-0/.npm/_logs/2018-08-01T12_19_34_084Z-debug.log
  builder for '/nix/store/2z4bg8v9ma100hsmd5lw3ibr65ahii7p-node-webpack-dev-server-2.11.2.drv' failed with exit code 2
  error: build of '/nix/store/0jdn0jvkczv57c1q2rg71wmswbkviglp-node-dependencies-hello-world-1.0.0.drv', '/nix/store/2z4bg8v9ma100hsmd5lw3ibr65ahii7p-node-webpack-dev-server-2.11.2.drv' failed